---
# This script assumes the 'zsh' package has already been installed by 00-packages.yaml
- name: Download oh-my-zsh installscript
  ansible.builtin.uri:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    return_content: yes
  register: ohmyzsh_installscript

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -s -- -y
    stdin: "{{ ohmyzsh_installscript.content }}"
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Configure ZSH theme
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^ZSH_THEME='
    line: "ZSH_THEME=\"{{ zsh_theme }}\""

- name: Configure ZSH plugins
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    regexp: '^plugins='
    line: "plugins={{ zsh_plugins }}"

- name: Configure ZSH as default
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
  become: yes
