---
- pause:
    prompt: Enter your windows username. Leaving it empty will end this play.
  register: windows_username

- name: End the play if username is empty
  ansible.builtin.meta: end_host
  when:
    - windows_username.user_input == ''

- name: Install build essentials
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - g++-mingw-w64-x86-64
      - git
    state: present
  become: true

- name: Create winhome link
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/winhome"
    state: link
    src: "/mnt/c/Users/{{ windows_username.user_input }}"

- name: Create .wsl folder (for .exe files otherwise they be slow)
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/winhome/.wsl"
    state: directory

- name: Clone repo
  ansible.builtin.git:
    repo: https://github.com/mgbowen/windows-fido-bridge.git
    dest: /tmp/windows-fido-bridge
  register: git_checkout

- name: Create build folder
  ansible.builtin.file:
    path: /tmp/windows-fido-bridge/build
    state: directory

- name: Cmake Configure
  ansible.builtin.command: cmake -DCMAKE_BUILD_TYPE=Release -DSK_API_VERSION=9 ..
  args:
    chdir: /tmp/windows-fido-bridge/build

- name: Compile stuff
  ansible.builtin.command: make
  args:
    chdir: /tmp/windows-fido-bridge/build

- name: Create link where exe file is going to be
  ansible.builtin.file:
    path: "/usr/local/lib/windowsfidobridge.exe"
    state: link
    src: "{{ ansible_env.HOME }}/winhome/.wsl/windowsfidobridge.exe"
    force: true
  become: true

- name: Install stuff
  ansible.builtin.command: make install
  args:
    chdir: /tmp/windows-fido-bridge/build
  become: true
